timezone: "Europe/Prague"
show_drafts: FALSE
future: FALSE
theme: jekyll-theme-architect
title: "Tetriminos"
description: "Filling my life with pieces of knowledge"

# collections
collections:
  - tutorials:
    output: true
    type: "tutorials"

# Setting defaults configurations
defaults:
  -
    scope:
      path: "" # apply this default to all files in the project
      type: ["pages", "posts", "tutorials"] # apply only to pages and posts
    values:
      layout: "default"
